### ISSUE TITLE
esoteric iOS errors

### ISSUE THREAD

**Issue by goozang-records** [sunshine-protocol/sunshine-bounty-ui#2]
I have to run it through XCode. I set up a developer profile and am using the associated email to sign for it. 

I hit this error https://github.com/flutter/flutter/issues/26123 so I'm going to try the workarounds discussed in the issue now. I'll follow up on this if any of the workarounds work...

Here are the commands and what they returned

```
➜  app git:(master) ✗ flutter run                 
 
Launching lib/main.dart on iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 8LQ93JZD9R
Running Xcode build...                                                  
                                                   
 ├─Assembling Flutter resources...                           2.7s
 └─Compiling, linking and signing...                         5.0s
Xcode build done.                                           11.5s
Could not install build/ios/iphoneos/Runner.app on 00008020-001C31D80E43002E.
Try launching Xcode and selecting "Product > Run" to fix the problem:   
  open ios/Runner.xcworkspace                                           
                                                                        
Installing and launching...                                        18.9s
Error launching application on iPhone.
➜  app git:(master) ✗
```

I tried running `flutter clean` and re-running and it still didn't solve it.

Even when I get the app to download to my phone, it just crashes after I open it.

**Comment by goozang-records** [comment]
Even when I run it through Xcode on an emulator, it gives the following error. I am running `flutter run --verbose` from the `apps` folder and I am getting this error.

```
[ +195 ms] [DEVICE LOG] 2020-04-20 15:39:58.086821-0400  localhost Runner[98357]: (Flutter) Failed to find assets path for
"Frameworks/App.framework/flutter_assets"
[        ] Failed to find assets path for "Frameworks/App.framework/flutter_assets"
[  +50 ms] [DEVICE LOG] 2020-04-20 15:39:58.138208-0400  localhost Runner[98357]: (CoreFoundation) Created Activity ID: 0xa8003, Description: Loading
Preferences From System CFPrefsD
[   +1 ms] [DEVICE LOG] 2020-04-20 15:39:58.140078-0400  localhost Runner[98357]: (Flutter) [VERBOSE-2:engine.cc(127)] Engine run configuration was
invalid.
[        ] [VERBOSE-2:engine.cc(127)] Engine run configuration was invalid.
[        ] [DEVICE LOG] 2020-04-20 15:39:58.140149-0400  localhost Runner[98357]: (Flutter) [VERBOSE-2:shell.cc(437)] Could not launch engine with
configuration.
[        ] [VERBOSE-2:shell.cc(437)] Could not launch engine with configuration.
[  +17 ms] [DEVICE LOG] 2020-04-20 15:39:58.158096-0400  localhost Runner[98357]: (Flutter) flutter: Observatory listening on
http://127.0.0.1:64827/nmdVJMzbwhk=/
[ +192 ms] [DEVICE LOG] 2020-04-20 15:39:58.350002-0400  localhost Runner[98357]: (RunningBoardServices) Created Activity ID: 0xa8004, Description:
didChangeInheritances
[  +12 ms] Observatory URL on device: http://127.0.0.1:64827/nmdVJMzbwhk=/
[   +8 ms] Connecting to service protocol: http://127.0.0.1:64827/nmdVJMzbwhk=/
[ +110 ms] Successfully connected to service protocol: http://127.0.0.1:64827/nmdVJMzbwhk=/
[   +2 ms] Sending to VM service: getVM({})
```

Note that this does not happen when I try to do the simple `flutter create`, `flutter run` commands. So I know the basic hello world example works and I know that this doesn't (with the emulator, I haven't even tried on the physical device since the time I posted the first error).

**Comment by dvc94ch** [comment]
Can you show me the full log? Have you included keystore.a into the build somehow? Also this is where you step in with you super Mac skills...

**Comment by goozang-records** [comment]
This is the relevant part of the `--verbose` logs. I'll figure it out, I think part of the problem might be that the identifier is `com.example.sunshine` and my email is `asinghchrony@protonmail.com` so the authentication requires the bundle identifier to take the form `com.protonmail.sunshine`

related: https://github.com/flutter/flutter/issues/33121 @dvc94ch the fix is to use the master branch of flutter as per https://github.com/flutter/flutter/issues/33121#issuecomment-596586351
```
[ +109 ms] [DEVICE LOG] Timestamp                       (process)[PID]    
[        ] [DEVICE LOG] 2020-04-20 15:39:57.878176-0400  localhost Runner[98357]: (RunningBoardServices) [com.apple.runningboard:connection]
Initializing connection
[   +1 ms] [DEVICE LOG] 2020-04-20 15:39:57.878388-0400  localhost Runner[98357]: (RunningBoardServices) [com.apple.runningboard:process] Removing all
cached process handles
[        ] [DEVICE LOG] 2020-04-20 15:39:57.878524-0400  localhost Runner[98357]: (RunningBoardServices) [com.apple.runningboard:connection] Sending
handshake request attempt #1 to server
[        ] [DEVICE LOG] 2020-04-20 15:39:57.878763-0400  localhost Runner[98357]: (RunningBoardServices) [com.apple.runningboard:connection] Creating
connection to com.apple.runningboard
[        ] [DEVICE LOG] 2020-04-20 15:39:57.880352-0400  localhost Runner[98357]: (RunningBoardServices) [com.apple.runningboard:connection] Handshake
succeeded
[        ] [DEVICE LOG] 2020-04-20 15:39:57.880454-0400  localhost Runner[98357]: (RunningBoardServices) [com.apple.runningboard:connection] Identity
resolved as application<com.example.sunshine>
[        ] [DEVICE LOG] 2020-04-20 15:39:57.880852-0400  localhost Runner[98357]: (FrontBoardServices) [com.apple.FrontBoard:Common] FBSWorkspace
connecting to endpoint : <BSServiceConnectionEndpoint: 0x6000000f5400; target: com.apple.frontboard.systemappservices; service:
com.apple.frontboard.workspace-service>
[        ] [DEVICE LOG] 2020-04-20 15:39:57.881595-0400  localhost Runner[98357]: (FrontBoardServices) [com.apple.FrontBoard:Common] FBSWorkspace
registering source: <FBSWorkspaceScenesClient: 0x6000031f40c0>
[        ] [DEVICE LOG] 2020-04-20 15:39:57.882644-0400  localhost Runner[98357]: (FrontBoardServices) [com.apple.FrontBoard:Common] FBSWorkspace
connected to endpoint : <BSServiceConnectionEndpoint: 0x6000000f5400; target: com.apple.frontboard.systemappservices; service:
com.apple.frontboard.workspace-service>
[        ] [DEVICE LOG] 2020-04-20 15:39:57.882856-0400  localhost Runner[98357]: (RunningBoardServices) [com.apple.runningboard:general] Added
observer for process assertions expiration warning: <_RBSExpirationWarningAssertion: 0x6000000e6380; identifier:
com.apple.runningboardservices.processExpirationWarningForHandle; reason: observation; valid: YES>
[   +1 ms] [DEVICE LOG] 2020-04-20 15:39:57.886150-0400  localhost Runner[98357]: (RunningBoardServices) Created Activity ID: 0xa8000, Description:
didChangeInheritances
[        ] [DEVICE LOG] 2020-04-20 15:39:57.886478-0400  localhost Runner[98357]: (FrontBoardServices) [com.apple.FrontBoard:Common] FBSWorkspace
already connected to endpoint : <BSServiceConnectionEndpoint: 0x6000000f46c0; target: com.apple.frontboard.systemappservices; service:
com.apple.frontboard.workspace-service>
[        ] [DEVICE LOG] 2020-04-20 15:39:57.887733-0400  localhost Runner[98357]: (CoreFoundation) Created Activity ID: 0xa8001, Description: Loading
Preferences From System CFPrefsD
[        ] [DEVICE LOG] 2020-04-20 15:39:57.888440-0400  localhost Runner[98357]: (CoreFoundation) Created Activity ID: 0xa8002, Description: Loading
Preferences From System CFPrefsD
[   +1 ms] [DEVICE LOG] 2020-04-20 15:39:57.890170-0400  localhost Runner[98357]: (libAccessibility.dylib) [com.apple.Accessibility:AXSupportCommon]
Retrieving resting unlock: 0
[        ] [DEVICE LOG] 2020-04-20 15:39:57.890471-0400  localhost Runner[98357]: (XCTTargetBootstrap) [com.apple.dt.xctest:Default] Registering for
test daemon availability notify post.
[        ] [DEVICE LOG] 2020-04-20 15:39:57.890589-0400  localhost Runner[98357]: (XCTTargetBootstrap) [com.apple.dt.xctest:Default] notify_get_state
check indicated test daemon not ready.
[ +195 ms] [DEVICE LOG] 2020-04-20 15:39:58.086821-0400  localhost Runner[98357]: (Flutter) Failed to find assets path for
"Frameworks/App.framework/flutter_assets"
[        ] Failed to find assets path for "Frameworks/App.framework/flutter_assets"
[  +50 ms] [DEVICE LOG] 2020-04-20 15:39:58.138208-0400  localhost Runner[98357]: (CoreFoundation) Created Activity ID: 0xa8003, Description: Loading
Preferences From System CFPrefsD
[   +1 ms] [DEVICE LOG] 2020-04-20 15:39:58.140078-0400  localhost Runner[98357]: (Flutter) [VERBOSE-2:engine.cc(127)] Engine run configuration was
invalid.
[        ] [VERBOSE-2:engine.cc(127)] Engine run configuration was invalid.
[        ] [DEVICE LOG] 2020-04-20 15:39:58.140149-0400  localhost Runner[98357]: (Flutter) [VERBOSE-2:shell.cc(437)] Could not launch engine with
configuration.
[        ] [VERBOSE-2:shell.cc(437)] Could not launch engine with configuration.
[  +17 ms] [DEVICE LOG] 2020-04-20 15:39:58.158096-0400  localhost Runner[98357]: (Flutter) flutter: Observatory listening on
http://127.0.0.1:64827/nmdVJMzbwhk=/
[ +192 ms] [DEVICE LOG] 2020-04-20 15:39:58.350002-0400  localhost Runner[98357]: (RunningBoardServices) Created Activity ID: 0xa8004, Description:
didChangeInheritances
[  +12 ms] Observatory URL on device: http://127.0.0.1:64827/nmdVJMzbwhk=/
[   +8 ms] Connecting to service protocol: http://127.0.0.1:64827/nmdVJMzbwhk=/
[ +110 ms] Successfully connected to service protocol: http://127.0.0.1:64827/nmdVJMzbwhk=/
[   +2 ms] Sending to VM service: getVM({})
[   +2 ms] Result: {type: VM, name: vm, architectureBits: 64, hostCPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz, operatingSystem: ios, targetCPU: x64,
version: 2.7.2 (Mon Mar 23 22:11:27 2020 +0100) on "ios_x64", _profilerMode: VM, _nativeZoneMemoryUsage: 0, pid: 98...
[   +4 ms] Sending to VM service: getIsolate({isolateId: isolates/351093007246663})
[   +2 ms] Sending to VM service: _flutter.listViews({})
[   +1 ms] Result: {type: Isolate, id: isolates/351093007246663, name: main, number: 351093007246663, _originNumber: 351093007246663, startTime:
1587411598092, _heaps: {new: {type: HeapSpace, name: new, vmName: Scavenger, collections: 0, avgCollectionPeriodMillis: 0...
[   +2 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x7f997101a420, isolate: {type: @Isolate, fixedId: true, id:
isolates/351093007246663, name: main.dart$main-351093007246663, number: 351093007246663}}]}
[   +4 ms] DevFS: Creating new filesystem on the device (null)
[        ] Sending to VM service: _createDevFS({fsName: app})
[  +11 ms] Result: {type: FileSystem, name: app, uri:
file:///Users/4meta5/Library/Developer/CoreSimulator/Devices/98871DF9-EDC1-4DD6-8FF5-FDA330281390/data/Containers/Data/Application/CAFA4875-EAC3-4037-B
CE2-44A860CBD6D6/tmp/appE7swlP/app/}
[        ] DevFS: Created new filesystem on the device
(file:///Users/4meta5/Library/Developer/CoreSimulator/Devices/98871DF9-EDC1-4DD6-8FF5-FDA330281390/data/Containers/Data/Application/CAFA4875-EAC3-4037-
BCE2-44A860CBD6D6/tmp/appE7swlP/app/)
[   +1 ms] Updating assets
[  +71 ms] Syncing files to device iPhone 8 Plus...
[   +1 ms] Scanning asset files
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +5 ms] /Users/4meta5/flutter-bin/flutter/bin/cache/dart-sdk/bin/dart
/Users/4meta5/flutter-bin/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/4meta5/flutter-bin/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter
-Ddart.developer.causal_async_stacks=true --output-dill /var/folders/hb/h88r8f51779_php5tx_pr__80000gn/T/flutter_tool.65o0Fp/app.dill --packages
/Users/4meta5/flutter-bin/sunshine-flutter/app/.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
[   +5 ms] <- compile package:sunshine/main.dart
[ +395 ms] [DEVICE LOG] 2020-04-20 15:39:58.997554-0400  localhost Runner[98357]: (RunningBoardServices) Created Activity ID: 0xa8005, Description:
didChangeInheritances
[+4798 ms] Updating files
[  +63 ms] DevFS: Sync finished
[        ] Syncing files to device iPhone 8 Plus... (completed in 5,272ms, longer than expected)
[        ] Synced 1.0MB.
[   +1 ms] Sending to VM service: _flutter.listViews({})
[   +1 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x7f997101a420, isolate: {type: @Isolate, fixedId: true, id:
isolates/351093007246663, name: main.dart$main-351093007246663, number: 351093007246663}}]}
[        ] <- accept
[        ] Connected to _flutterView/0x7f997101a420.
[   +1 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[        ] An Observatory debugger and profiler on iPhone 8 Plus is available at: http://127.0.0.1:64827/nmdVJMzbwhk=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+363466 ms] Initializing hot reload...
```

**Comment by goozang-records** [comment]
I do think this is the best build log yet, but it is still an error. I guess you were right that I need to compile the keystore library and include it. I'll close this once I figure it out.

```
Project base configurations detected, removing.
Running pod install...                                              1.3s
Running Xcode build...                                                  
                                                   
 └─Compiling, linking and signing...                         9.9s
Xcode build done.                                           25.7s
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following ArgumentError was thrown building Builder(dirty):
flutter: Invalid argument(s): Failed to load dynamic library (dlopen(libkeystore.so, 1): image not found)
flutter:
flutter: The relevant error-causing widget was:
flutter:   Builder file:///Users/4meta5/flutter-bin/sunshine-flutter/app/lib/main.dart:81:22
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:13:55)
flutter: #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
flutter: #2      _dynamicLibrary (package:keystore/generated.dart:7:63)
flutter: #3      _dynamicLibrary (package:keystore/generated.dart:7:26)
flutter: #4      _keystore_from_keyfile (package:keystore/generated.dart:63:60)
flutter: #5      _keystore_from_keyfile (package:keystore/generated.dart:63:35)
flutter: #6      keystore_from_keyfile (package:keystore/generated.dart:60:10)
flutter: #7      new Keystore.fromKeyfile (package:keystore/keystore.dart:22:21)
flutter: #8      BlocSetup.build.<anonymous closure>.<anonymous closure> (package:sunshine/main.dart:79:33)
flutter: #9      _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:405:33)
flutter: #10     _InheritedProviderScopeMixin.value (package:provider/src/inherited_provider.dart:295:33)
flutter: #11     Provider.of (package:provider/src/provider.dart:233:29)
flutter: #12     RepositoryProvider.of (package:flutter_bloc/src/repository_provider.dart:59:23)
flutter: #13     BlocSetup.build.<anonymous closure>.<anonymous closure> (package:sunshine/main.dart:83:55)
flutter: #14     Builder.build (package:flutter/src/widgets/basic.dart:7006:48)
flutter: #15     StatelessElement.build (package:flutter/src/widgets/framework.dart:4580:28)
flutter: #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4506:15)
flutter: #17     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
flutter: #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4485:5)
flutter: #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
flutter: #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
flutter: #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
flutter: #23     _InheritedProviderScopeMixin.performRebuild (package:provider/src/inherited_provider.dart:220:11)
flutter: #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
flutter: #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4485:5)
flutter: #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
flutter: ...     Normal element mounting (7 frames)
flutter: #33     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
flutter: #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
flutter: #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3215:20)
flutter: #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
flutter: #37     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4679:11)
flutter: #38     Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
flutter: #39     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
flutter: #40     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:864:20)
flutter: #41     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
flutter: #42     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1074:15)
flutter: #43     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1013:9)
flutter: #44     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:929:5)
flutter: #48     _invoke (dart:ui/hooks.dart:261:10)
flutter: #49     _drawFrame (dart:ui/hooks.dart:219:3)
flutter: (elided 3 frames from dart:async)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
Syncing files to device iPhone 8 Plus...                           134ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on iPhone 8 Plus is available at: http://127.0.0.1:50271/lBX652AUY_Q=/
```

**Comment by goozang-records** [comment]
Apparently this should solve it https://stackoverflow.com/questions/61144408/failed-to-find-assets-path-for-frameworks-app-framework-flutter-assets/61153671#61153671 -- I'll try it tomorrow morning probably

**Comment by shekohex** [comment]
closing in favor of #3
